[package]
name = "rustorch"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix = { path = "crates/Matrix" }
Database = { path = "crates/Database" }
NeuralNetworks = { path = "crates/NeuralNetworks" }

[workspace]
members = [
    "crates/Matrix",
    "crates/Database",
    "crates/NeuralNetworks"
]
