[package]
name = "NeuralNetworks"
version = "0.1.0"
edition = "2024"

[dependencies]
matrix = { path = "../Matrix" }
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.8"

[dev-dependencies]
approx = "0.5"
