[package]
name = "tensor"
version = "0.1.0"
edition = "2024"

[dependencies]
num_cpus = "1.17.0"
rand = "0.8"
rand_pcg = "0.3"
rayon = "1.10.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
target-cpu = "native"
